# Generated by Django 5.1.6 on 2025-04-09 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_stripe_customer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='stripe_last_intent_id',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True, unique=True),
        ),
    ]
