# Generated by Django 5.1.6 on 2025-05-25 18:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_stripe_last_intent_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('is_suspended', models.BooleanField(default=False)),
                ('suspension_end', models.DateTimeField(blank=True, null=True)),
                ('has_verified_email', models.BooleanField(default=False)),
                ('mfa_secret', models.CharField(blank=True, max_length=16, null=True)),
                ('mfa_enabled', models.BooleanField(default=False)),
                ('stripe_customer_id', models.CharField(blank=True, editable=False, max_length=255, null=True, unique=True)),
                ('stripe_last_intent_id', models.CharField(blank=True, editable=False, max_length=255, null=True, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
