# Generated by Django 5.1.6 on 2025-05-25 18:31

from django.db import migrations


def migrate_stripe_data(apps, schema_editor):
    Profile = apps.get_model('users', 'Profile')
    Account = apps.get_model('users', 'Account')
    
    for profile in Profile.objects.filter(stripe_customer_id__isnull=False):
        # Get or create Account without triggering save()
        account, created = Account.objects.get_or_create(
            user=profile.user,
            defaults={
                'stripe_customer_id': profile.stripe_customer_id,
                'stripe_last_intent_id': profile.stripe_last_intent_id
            }
        )
        
        # Only update if account already existed
        if not created:
            account.stripe_customer_id = profile.stripe_customer_id
            account.stripe_last_intent_id = profile.stripe_last_intent_id
            # Bypass the save() method to prevent Stripe customer creation
            Account.objects.filter(pk=account.pk).update(
                stripe_customer_id=profile.stripe_customer_id,
                stripe_last_intent_id=profile.stripe_last_intent_id
            )


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_account'),
    ]

    operations = [
        migrations.RunPython(migrate_stripe_data),
    ]
