# Generated by Django 5.1.6 on 2025-05-25 18:31

from django.db import migrations
from users.utils import get_or_create_stripe_customer

def migrate_stripe_data(apps, schema_editor):
    Profile = apps.get_model('users', 'Profile')
    Account = apps.get_model('users', 'Account')
    
    for profile in Profile.objects.all():
        # Get or create Account without triggering save()
        account, created = Account.objects.get_or_create(user=profile.user)
        
        # Migrate existing Stripe data if available
        if profile.stripe_customer_id:
            account.stripe_customer_id = profile.stripe_customer_id
            account.stripe_last_intent_id = profile.stripe_last_intent_id
        # Only create new Stripe customer if profile never had one
        elif not account.stripe_customer_id:
            account.stripe_customer_id = get_or_create_stripe_customer(profile.user)
        
        # Save with direct SQL update to bypass model save()
        Account.objects.filter(pk=account.pk).update(
            stripe_customer_id=account.stripe_customer_id,
            stripe_last_intent_id=account.stripe_last_intent_id
        )


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_migrate_stripe_data'),
    ]

    operations = [
        migrations.RunPython(migrate_stripe_data),
    ]
