# Generated by Django 5.1.6 on 2025-05-29 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_profile_stripe_customer_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='mfa_verified',
            field=models.BooleanField(default=False),
        ),
    ]
