# Generated by Django 5.1.6 on 2025-05-29 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_account_mfa_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='mfa_verified',
        ),
    ]
