# Generated by Django 5.1.6 on 2025-06-04 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_account_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='mfa_secret',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
