# Generated by Django 5.1.6 on 2025-06-04 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_account_mfa_secret'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='phone_number',
        ),
    ]
