# Generated by Django 5.1.6 on 2025-06-26 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_remove_profile_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='deletion_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
