# Generated by Django 5.1.6 on 2025-07-21 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_remove_account_deletion_task_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='deletion_phase',
            field=models.CharField(choices=[('pending', 'Pending Deletion'), ('stripe_started', 'Stripe Deletion Started'), ('stripe_completed', 'Stripe Deletion Completed'), ('user_deletable', 'User Ready for Deletion'), ('completed', 'User has been Deleted'), ('failed', 'Failed to fully Delete the User')], default='pending', max_length=20),
        ),
    ]
